FROM node:latest
run npm install -g serve
ENV NPM_CONFIG_PREFIX=/home/node/.npm-global


RUN mkdir -p  /usr/src/app
WORKDIR /usr/src/app
COPY package.json /usr/src/app


RUN npm install --silent

ADD src /usr/src/app/src
ADD public /usr/src/app/public

RUN npm run build


CMD ["serve","-s", "build"]